FROM ubuntu:bionic

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3 \
    net-tools \
    iputils-ping \
    iproute2 \
    python3-pip

COPY ./clients/requirements.txt .
COPY ./clients/client_ddos.py .

RUN pip3 install --no-cache-dir -r requirements.txt

CMD ["python3", "client_ddos.py"]