FROM ubuntu:bionic

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3 \
    net-tools \
    iputils-ping \
    iproute2 \
    python3-pip


COPY ./tracer/requirements.txt .
COPY ./tracer/tracer.py .

RUN pip3 install --no-cache-dir -r requirements.txt

EXPOSE 5001

CMD ["python3", "tracer.py"]