FROM ubuntu:bionic

WORKDIR /app

RUN apt-get update && apt-get install -y \
    python3 \
    net-tools \
    iputils-ping \
    iproute2 \
    python3-pip

COPY ./server/requirements.txt .
COPY ./server/servWeb.py .

RUN pip3 install --no-cache-dir -r requirements.txt

EXPOSE 5000